<h1 style="text-align: center;"><a href="https://fivethirtyeight.com/features/its-time-to-give-basketballs-other-goat-her-due/">She Got Next.</a></h1>
<h3 style="text-align: center;"> Michael Patel </h3>

In [1]:
import numpy as np
import pandas as pd
import altair as alt

data = pd.read_csv("wnba-player-stats.csv")
pd.set_option('display.max_columns', 500)

In [2]:
data # 3883 player entries, includes their stats for each season, from 1997 thru 2019.

,player_ID,Player,year_ID,Age,Tm,tm_gms,Tm_Net_Rtg,Pos,G,MP,MP_pct,PER,TS_pct,ThrPAr,FTr,ORB_pct,TRB_pct,AST_pct,STL_pct,BLK_pct,TOV_pct,USG_pct,OWS,DWS,WS,WS40,Composite_Rating,Wins_Generated
0,montgre01w,Renee Montgomery,2019,32,ATL,34,-9.8,G,34,949,69.5%,11.1,0.520,0.727,0.176,1.0,4.1,18.0,1.7,0.5,16.8,17.5,0.4,0.5,0.9,0.039,-2.4,1.22
1,williel01w,Elizabeth Williams,2019,26,ATL,34,-9.8,C-F,32,909,66.6%,16.7,0.521,0.000,0.477,11.4,12.1,7.8,1.4,4.7,12.9,15.9,1.6,1.0,2.7,0.117,0.6,2.51
2,sykesbr01w,Brittney Sykes,2019,25,ATL,34,-9.8,G,34,880,64.5%,11.3,0.445,0.308,0.259,3.0,9.1,19.6,1.2,1.5,14.8,23.1,-0.8,0.8,0.0,-0.001,-3.4,0.70
3,hayesti01w,Tiffany Hayes,2019,29,ATL,34,-9.8,G,29,817,59.9%,15.1,0.497,0.313,0.340,2.7,5.7,21.9,1.8,0.8,14.0,27.1,0.5,0.6,1.0,0.050,-1.5,1.45
4,brelaje01w,Jessica Breland,2019,31,ATL,34,-9.8,F,33,767,56.2%,15.2,0.425,0.138,0.120,5.7,16.6,14.2,2.8,3.6,11.6,18.9,-0.4,1.9,1.5,0.076,-0.8,1.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3878,cartede01w,Deborah Carter,1997,25,UTA,28,-13.8,G-F,19,286,25.3%,10.1,0.431,0.110,0.171,8.5,10.7,5.9,2.4,0.3,16.2,16.4,0.0,0.0,0.0,0.002,-4.0,0.15
3879,kossgr01w,Greta Koss,1997,23,UTA,28,-13.8,F,13,268,23.7%,9.1,0.610,0.103,0.552,5.0,8.0,7.0,1.8,1.2,33.3,9.0,0.1,-0.1,0.0,0.005,-4.1,0.13
3880,hicksje01w,Jessie Hicks,1997,25,UTA,28,-13.8,C-F,26,263,23.3%,12.4,0.477,0.013,0.200,7.2,7.9,8.5,2.6,3.3,12.1,16.8,0.4,0.0,0.4,0.060,-2.1,0.38
3881,scottra01w,Raegan Scott,1997,21,UTA,28,-13.8,F-C,8,43,3.8%,16.0,0.432,0.000,0.154,10.3,9.4,4.9,1.2,5.5,0.0,14.4,0.1,0.0,0.1,0.092,-0.6,0.09
3882,compame01w,Megan Compain,1997,21,UTA,28,-13.8,G,4,19,1.7%,0.0,0.000,0.667,0.000,0.0,3.0,17.9,11.2,4.2,50.0,14.1,-0.2,0.1,-0.1,-0.228,-11.8,-0.06

In [3]:
data1 = pd.read_csv("wnba-team-elo-ratings.csv")
data1 # team data for each game, from 1997 thru 2019

,season,date,team1,team2,name1,name2,neutral,playoff,score1,score2,elo1_pre,elo2_pre,elo1_post,elo2_post,prob1,is_home1
0,2019,10/10/2019,WAS,CON,Washington Mystics,Connecticut Sun,0,1,89,78,1684,1634,1692,1627,0.718,1
1,2019,10/10/2019,CON,WAS,Connecticut Sun,Washington Mystics,0,1,78,89,1634,1684,1627,1692,0.282,0
2,2019,10/8/2019,WAS,CON,Washington Mystics,Connecticut Sun,0,1,86,90,1693,1626,1684,1634,0.476,0
3,2019,10/8/2019,CON,WAS,Connecticut Sun,Washington Mystics,0,1,90,86,1626,1693,1634,1684,0.524,1
4,2019,10/6/2019,WAS,CON,Washington Mystics,Connecticut Sun,0,1,94,81,1671,1648,1693,1626,0.399,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10483,1997,6/21/1997,SAC,LVA,Sacramento Monarchs,Utah Starzz,0,0,73,61,1500,1500,1521,1479,0.387,0
10484,1997,6/21/1997,NYL,LAS,New York Liberty,Los Angeles Sparks,0,0,67,57,1500,1500,1519,1481,0.387,0
10485,1997,6/21/1997,LAS,NYL,Los Angeles Sparks,New York Liberty,0,0,57,67,1500,1500,1481,1519,0.613,1
10486,1997,6/21/1997,LVA,SAC,Utah Starzz,Sacramento Monarchs,0,0,61,73,1500,1500,1479,1521,0.613,1
10487,1997,6/21/1997,CLE,HOU,Cleveland Rockers,Houston Comets,0,0,56,76,1500,1500,1470,1530,0.613,1